---
abstract: 'MogileFS Server class for representing networks based on host IPs.'
author:
  - 'Jonathan Steinert <hachi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MogileFS-Network
no_index:
  directory:
    - t
    - inc
requires:
  MogileFS::Server: 2.50
  Net::Netmask: 0
  Net::Patricia: 0
version: 0.06
