--- #YAML:1.0
name:               MogileFS-Network
version:            0.05
abstract:           MogileFS Server class for representing networks based on host IPs.
author:
    - Jonathan Steinert <hachi@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MogileFS::Server:  2.50
    Net::Netmask:      0
    Net::Patricia:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
